### ISSUE TITLE
Reportar cantidad de veces que cada revista ha sido reservada y devuelta a lo largo del tiempo, ordenadas por popularidad 

### ISSUE THREAD

**Issue by eze6532** [ig-revistas/ig-revistas#9]
Epica:  Reportes #23

### Descripcion
**Como**  administrador/operador ,   
**Quiero**  ver un reporte cantidad de veces que cada revista ha sido reservada y devuelta a lo largo del tiempo, ordenadas por popularidad .
**Para**  saber cuales fueron las revistas mas consumidas. 

### Criterios de Aceptacion
  - El operador debe poder generar un reporte con la lista de cantidad de reservas devueltas por revista.
  - El reporte debe incluir numero de veces prestada y titulo de la revista .

### Tareas
  - [x] Desarrollar un servicio que devuelva los datos.
  - [x] Crear una tabla html que muestre los datos.

**Comment by gonzaloandrade217** [comment]
select count(1) as count_prestamo, rev.titulo ,rev.id 
from reserva res,
revista rev
where res.id_revista = rev.id and res.estado = 'APROBADA'
group by rev.id 
order by count_prestamo desc;
